name: gst_demo
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=2.3.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  provider_architecture: ^1.0.3
  responsive_builder: ^0.1.4
  provider: ^3.2.0
  logger: ^0.7.0+2
  get_it: ^3.0.3
  equatable: ^1.0.1
  sqflite: ^1.2.0
  path: ^1.6.4
  hive: ^1.3.0
  hive_flutter: ^0.3.0+1
  path_provider: ^1.6.0
  intl: ^0.16.1
  uuid_enhanced: ^3.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.7.0
  build_runner: ^1.7.3
flutter:
  uses-material-design: true
